set(ARCH ${CMAKE_SYSTEM_PROCESSOR})
if(ARCH STREQUAL "AMD64")
    set(ARCH "x86_64")
endif()

set(PLATFORM UNDEFINED)
if(CMAKE_SYSTEM_NAME STREQUAL "Windows")
    set(PLATFORM "windows")
elseif(CMAKE_SYSTEM_NAME STREQUAL "Linux")
    set(PLATFORM "linux")
elseif(CMAKE_SYSTEM_NAME STREQUAL "Darwin")
    set(PLATFORM "macos")
else()
    message(FATAL_ERROR "Unsupported platform")
endif()